name: Golang Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'  # Replace with the desired Go version

    - name: Initialize
      run: make initialize

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Run
      run: make run
